<section class="page-support">
    <h2 class="page-support-sub-title"><?php /* @escapeNotVerified */ echo __('Technical Support'); ?></h2>
    <p class="tutorial-description">
        <?php echo __("Access out ticket system below or by link <a href='%1' target='_blank'>%1</a>", "https://central.tecsecret.com.br/", "https://central.tecsecret.com.br/") ?>
    </p>
    <iframe src="https://central.tecsecret.com.br/" height="600" width="100%" frameborder="0"></iframe>